"""Post Deletion

Revision ID: 2bd6aed2956e
Revises: a51e34954831
Create Date: 2026-03-16 22:52:20.867462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 



# revision identifiers, used by Alembic.
revision: str = '2bd6aed2956e'
down_revision: Union[str, Sequence[str], None] = 'a51e34954831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_comments_post_id_fkey'), 'post_comments', type_='foreignkey')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_likes_post_id_fkey'), 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_shares_post_id_fkey'), 'post_shares', type_='foreignkey')
    op.create_foreign_key(None, 'post_shares', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_shares', type_='foreignkey')
    op.create_foreign_key(op.f('post_shares_post_id_fkey'), 'post_shares', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key(op.f('post_likes_post_id_fkey'), 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.create_foreign_key(op.f('post_comments_post_id_fkey'), 'post_comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
