"""Komek and location

Revision ID: 4d3b2d1dffa3
Revises: 96f9ad0f9952
Create Date: 2026-03-27 21:20:57.309411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3b2d1dffa3'
down_revision: Union[str, Sequence[str], None] = '96f9ad0f9952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_helps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('TUTOR', 'PHYSICAL', 'RENTAL', 'OTHER', name='helpcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request_helps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'applicant_id', name='unique_help_application')
    )
    op.drop_constraint(op.f('post_comments_post_id_fkey'), 'post_comments', type_='foreignkey')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_likes_post_id_fkey'), 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_shares_post_id_fkey'), 'post_shares', type_='foreignkey')
    op.create_foreign_key(None, 'post_shares', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_constraint(None, 'post_shares', type_='foreignkey')
    op.create_foreign_key(op.f('post_shares_post_id_fkey'), 'post_shares', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key(op.f('post_likes_post_id_fkey'), 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.create_foreign_key(op.f('post_comments_post_id_fkey'), 'post_comments', 'posts', ['post_id'], ['id'])
    op.drop_table('help_applications')
    op.drop_table('request_helps')
    # ### end Alembic commands ###
