"""post flag and user ban

Revision ID: 652fab2a686b
Revises: dd0ead3e38a7
Create Date: 2026-04-05 17:56:28.120436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 



# revision identifiers, used by Alembic.
revision: str = '652fab2a686b'
down_revision: Union[str, Sequence[str], None] = 'dd0ead3e38a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.execute("UPDATE posts SET is_flagged = FALSE WHERE is_flagged IS NULL")
    op.alter_column('posts', 'is_flagged', nullable=False)

    op.add_column('posts', sa.Column('flag_reason', sa.VARCHAR(), nullable=True))

    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_banned = FALSE WHERE is_banned IS NULL")
    op.alter_column('users', 'is_banned', nullable=False)

    op.add_column('users', sa.Column('ban_reason', sa.VARCHAR(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'is_banned')
    op.drop_column('posts', 'flag_reason')
    op.drop_column('posts', 'is_flagged')
    # ### end Alembic commands ###
