"""RBAC and Verifier

Revision ID: dd0ead3e38a7
Revises: 4d3b2d1dffa3
Create Date: 2026-03-31 20:53:02.915700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd0ead3e38a7'
down_revision: Union[str, Sequence[str], None] = '4d3b2d1dffa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_compressed_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_data', postgresql.BYTEA(), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('compressed_size', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_table('user_compressed_images')
    # ### end Alembic commands ###
